
development:
  adapter: postgresql
  encoding: utf8
  database: lessli
  username: postgres
  password: 111111
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: lessli
  username: postgres
  password: 111111
  host: localhost